export const GET_ALL_DRIVERS = 'GET_ALL_DRIVERS';
export const GET_DRIVERS_BY_NAME = 'GET_DRIVERS_BY_NAME';
export const DETAIL_BY_ID='DETAIL_BY_ID';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const ORDER_BY = 'ORDER_BY';
export const TEAM_LIST = 'TEAM_LIST';
export const FILTER_BY_TEAMS = 'FILTER_BY_TEAMS';
export const FILTER_BY_ORIGIN = 'FILTER_BY_DATE';
export const NEW_DRIVER='NEW_DRIVER'